host = "localhost"
port = 6060

[db_settings]
connection_string = "postgresql+asyncpg://postgres:testpwd@localhost:5433/demo_db"

[security]
password_hash_algorithm = "sha3-256"
password_hash_iterations = 500000
jwt_signing_secret = "DEMO_SECRET"
access_token_alive_time_in_seconds = 604800
allowed_cors_domains = [
    "http://localhost:6060",
    "https://localhost:7023"
]