"""Add more relations for roles and resources

Revision ID: 76dda91c7bd4
Revises: 470730bd2e92
Create Date: 2025-08-14 12:45:33.044970

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '76dda91c7bd4'
down_revision: Union[str, Sequence[str], None] = '470730bd2e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assigned_roles_role_id_fkey'), 'assigned_roles', type_='foreignkey')
    op.create_foreign_key(None, 'assigned_roles', 'role', ['role_id'], ['role_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('roles_permissions_role_id_fkey'), 'roles_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'roles_permissions', 'role', ['role_id'], ['role_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('roles_permissions_role_id_fkey'), 'roles_permissions', 'role', ['role_id'], ['role_id'])
    op.drop_constraint(None, 'assigned_roles', type_='foreignkey')
    op.create_foreign_key(op.f('assigned_roles_role_id_fkey'), 'assigned_roles', 'role', ['role_id'], ['role_id'])
    # ### end Alembic commands ###
